
//phx grid
export const PHX_GRID_READ_STARTED = 'PHX_GRID_READ_STARTED';
export const PHX_GRID_READ_ENDED = 'PHX_GRID_READ_ENDED';
export const PHX_GRID_READING = 'PHX_GRID_READING';

export const PHX_GRID_SORT_STARTED = 'PHX_GRID_SORT_STARTED';
export const PHX_GRID_SORT_ENDED = 'PHX_GRID_SORT_ENDED';
export const PHX_GRID_SORTING = 'PHX_GRID_SORTING';

export const PHX_GRID_PAGE_CHANGE_STARTED = 'PHX_GRID_PAGE_CHANGE_STARTED';
export const PHX_GRID_PAGE_CHANGE_ENDED = 'PHX_GRID_PAGE_CHANGE_ENDED';
export const PHX_GRID_PAGE_CHANGING = 'PHX_GRID_PAGE_CHANGING';




//phx grid item

export const PHX_GRID_ITEM_CREATE = 'PHX_GRID_ITEM_CREATE';
export const PHX_GRID_ITEM_READ = 'PHX_GRID_ITEM_READ';
export const PHX_GRID_ITEM_UPDATE = 'PHX_GRID_ITEM_UPDATE';
export const PHX_GRID_ITEM_DELETE = 'PHX_GRID_ITEM_DELETE';


//youtube
export const YOUTUBE_SCRIPTS_RENDER_STARTED = 'YOUTUBE_SCRIPTS_RENDER_STARTED';
export const YOUTUBE_SCRIPTS_RENDER_ENDED = 'YOUTUBE_SCRIPTS_RENDER_ENDED';
export const YOUTUBE_SCRIPTS_RENDERING = 'YOUTUBE_PLAYER_RENDER_STARTED';

export const YOUTUBE_PLAYER_RENDER_STARTED = 'YOUTUBE_PLAYER_RENDER_STARTED';
export const YOUTUBE_PLAYER_RENDER_ENDED = 'YOUTUBE_PLAYER_RENDER_ENDED';
export const YOUTUBE_PLAYER_RENDERING = 'YOUTUBE_PLAYER_RENDERING';

export const YOUTUBE_PLAYER_PLAY = 'YOUTUBE_PLAYER_PLAY';
export const YOUTUBE_PLAYER_STOP = 'YOUTUBE_PLAYER_STOP';
export const YOUTUBE_PLAYER_READY = 'YOUTUBE_PLAYER_READY';






 